name: ghpages

on:
  push:
    branches: ['deploy']

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    steps:
      - name: Use source code in repository
        uses: actions/checkout@v3

      - name: Use node 22 runtime.
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Cache dependency in yarn cache directory
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Check if cache is hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo 'Yarn cache has been hit'

      - name: Install dependency
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
        env:
          CI: false
          REACT_APP_URL_API_SERVER: ${{ vars.REACT_APP_URL_API_SERVER }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
